sudo: false

language: php

matrix:
  include:
    - name: '[REQUIRE_CHECK] With Locked Dependencies'
      php: '7.3'
      env: require=1
    - name: '[REQUIRE_CHECK] With Lowest Dependencies'
      php: '7.3'
      env: require=1 dependencies=lowest
    - name: '[REQUIRE_CHECK] With Highest Dependencies'
      php: '7.3'
      env: require=1 dependencies=highest

    - name: '[CS] PHP 7.3 With Locked Dependencies'
      php: '7.3'
      env: cs=1
    - name: '[CS] PHP 7.3 With Lowest Dependencies'
      php: '7.3'
      env: cs=1 dependencies=lowest
    - name: '[CS] PHP 7.3 With Highest Dependencies'
      php: '7.3'
      env: cs=1 dependencies=highest
    - name: '[CS] PHP Nightly With Locked Dependencies'
      php: nightly
      env: cs=1
    - name: '[CS] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: cs=1 dependencies=lowest
    - name: '[CS] PHP Nightly With Highest Dependencies'
      php: nightly
      env: cs=1 dependencies=highest

    - name: '[UNIT] PHP 7.3 With Locked Dependencies'
      php: '7.3'
      env: unit=1
    - name: '[UNIT] PHP 7.3 With Lowest Dependencies'
      php: '7.3'
      env: dependencies=lowest unit=1
    - name: '[UNIT] PHP 7.3 With Highest Dependencies'
      php: '7.3'
      env: dependencies=highest unit=1
    - name: '[UNIT] PHP Nightly With Locked Dependencies'
      php: nightly
      env: unit=1
    - name: '[UNIT] PHP Nightly With Highest Dependencies'
      php: nightly
      env: dependencies=highest unit=1
    - name: '[UNIT] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: dependencies=lowest unit=1

    - name: '[INTEGRATION] PHP 7.3 With Locked Dependencies'
      php: '7.3'
      env: integration=1
    - name: '[INTEGRATION] PHP 7.3 With Lowest Dependencies'
      php: '7.3'
      env: dependencies=lowest integration=1
    - name: '[INTEGRATION] PHP 7.3 With Highest Dependencies'
      php: '7.3'
      env: dependencies=highest integration=1
    - name: '[INTEGRATION] PHP Nightly With Locked Dependencies'
      php: nightly
      env: integration=1
    - name: '[INTEGRATION] PHP Nightly With Highest Dependencies'
      php: nightly
      env: dependencies=highest integration=1
    - name: '[INTEGRATION] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: dependencies=lowest integration=1

    - name: '[INFECTION] PHP 7.3 With Locked Dependencies'
      php: '7.3'
      env: infection=1
    - name: '[INFECTION] PHP 7.3 With Lowest Dependencies'
      php: '7.3'
      env: infection=1 dependencies=lowest
    - name: '[INFECTION] PHP 7.3 With Highest Dependencies'
      php: '7.3'
      env: infection=1 dependencies=highest
    - name: '[INFECTION] PHP Nightly With Locked Dependencies'
      php: nightly
      env: infection=1
    - name: '[INFECTION] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: infection=1 dependencies=lowest
    - name: '[INFECTION] PHP Nightly With Highest Dependencies'
      php: nightly
      env: infection=1 dependencies=highest

    - name: '[PHPSTAN] PHP 7.3 With Locked Dependencies'
      php: '7.3'
      env: phpstan=1
    - name: '[PHPSTAN] PHP 7.3 With Lowest Dependencies'
      php: '7.3'
      env: phpstan=1 dependencies=lowest
    - name: '[PHPSTAN] PHP 7.3 With Highest Dependencies'
      php: '7.3'
      env: phpstan=1 dependencies=highest
    - name: '[PHPSTAN] PHP Nightly With Locked Dependencies'
      php: nightly
      env: phpstan=1
    - name: '[PHPSTAN] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: phpstan=1 dependencies=lowest
    - name: '[PHPSTAN] PHP Nightly With Highest Dependencies'
      php: nightly
      env: phpstan=1 dependencies=highest
  allow_failures:
    - name: '[CS] PHP Nightly With Locked Dependencies'
      php: nightly
      env: cs=1
    - name: '[CS] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: cs=1 dependencies=lowest
    - name: '[CS] PHP Nightly With Highest Dependencies'
      php: nightly
      env: cs=1 dependencies=highest

    - name: '[UNIT] PHP Nightly With Locked Dependencies'
      php: nightly
      env: unit=1
    - name: '[UNIT] PHP Nightly With Highest Dependencies'
      php: nightly
      env: dependencies=highest unit=1
    - name: '[UNIT] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: dependencies=lowest unit=1

    - name: '[INTEGRATION] PHP Nightly With Locked Dependencies'
      php: nightly
      env: integration=1
    - name: '[INTEGRATION] PHP Nightly With Highest Dependencies'
      php: nightly
      env: dependencies=highest integration=1
    - name: '[INTEGRATION] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: dependencies=lowest integration=1

    - name: '[INFECTION] PHP Nightly With Locked Dependencies'
      php: nightly
      env: infection=1
    - name: '[INFECTION] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: infection=1 dependencies=lowest
    - name: '[INFECTION] PHP Nightly With Highest Dependencies'
      php: nightly
      env: infection=1 dependencies=highest

    - name: '[PHPSTAN] PHP Nightly With Locked Dependencies'
      php: nightly
      env: phpstan=1
    - name: '[PHPSTAN] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: phpstan=1 dependencies=lowest
    - name: '[PHPSTAN] PHP Nightly With Highest Dependencies'
      php: nightly
      env: phpstan=1 dependencies=highest
services:
  - redis-server

before_install:
  - phpenv config-rm xdebug.ini || echo "No xdebug config."
  - composer self-update

install:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
  - chmod +x php-coveralls.phar

before_script:
  - if [ -z "$dependencies" ]; then travis_retry composer install -n; fi;
  - if [ "$dependencies" = "lowest" ]; then travis_retry composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then travis_retry composer update -n; fi;
  - if [ "$infection" = 1 ]; then wget https://github.com/infection/infection/releases/download/0.12.2/infection.phar; fi;
  - if [ "$infection" = 1 ]; then wget https://github.com/infection/infection/releases/download/0.12.2/infection.phar.asc; fi;
  - if [ "$infection" = 1 ]; then gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 493B4AA0; fi;
  - if [ "$infection" = 1 ]; then gpg --with-fingerprint --verify infection.phar.asc infection.phar; fi;
  - if [ "$infection" = 1 ]; then chmod +x infection.phar; fi;

script:
  - if [ "$unit" = 1 ]; then phpdbg -qrr vendor/bin/phpunit --testsuite HarmonIOCacheUnitTestSuite --coverage-text --coverage-clover build/logs/clover.xml; fi;
  - if [ "$integration" = 1 ]; then phpdbg -qrr vendor/bin/phpunit --testsuite HarmonIOCacheIntegrationTestSuite --coverage-text --coverage-clover build/logs/clover.xml; fi;
  - if [ "$cs" = 1 ]; then vendor/bin/phpcs -s; fi;
  - if [ "$require" = 1 ]; then vendor/bin/composer-require-checker check; fi;
  - if [ "$infection" = 1 ]; then phpdbg -qrr ./infection.phar --min-msi=100 --min-covered-msi=100 --threads=4 --show-mutations; fi;
  - if [ "$phpstan" = 1 ]; then vendor/bin/phpstan analyse src --level max; fi;

after_success:
  - if [ "$unit" = 1 ]; then travis_retry php php-coveralls.phar; fi;
